### ISSUE TITLE
Question regarding CI

### ISSUE THREAD

**Issue by SimonBiggs** [xlwings/xlwings#1064]
I have been trying to work out if anyone has a solution for testing UDFs within Excel during tests on CI such as Azure pipelines and Travis.

I suspect it just might not be possible, but if anyone has any suggestions I'm keen to hear :)

**Comment by Colin-b** [comment]
1) Your test agent needs to run on Microsoft Windows with Microsoft Excel
installed. (This setup can be done beforehand or even on the fly, I'm sure
you can find a CLI to do so, I can't imagine huge companies installing it
manually desk by desk)

2) Generate the excel file containing your UDFs (many ways of doing it,
using xlwings CLI, using VBA, ...)

3) Add your formulas with parameters in cells and execute them (pretty sure
you can find a python module to manipulate the excel file and add them, or
it can even be done before step 2 and then adding UDF so that call will
work)

3) Assert the result content in Microsoft Excel. (You can obviously assert
even more in case your code also perform extra action instead of simply
returning a result)

So nothing specific here but I can't see a blocking step preventing to run
CI.

**Comment by fzumstein** [comment]
Hi @SimonBiggs. We're about to launch a private beta of an Excel CI service. The problems with any of the existing CI services (like Azure/Travis etc) is that you can't install Excel on them. Another issue is that you need to make sure that your Excel license covers that usage. Our initial offering will be for GitLab runners. Please send me an email (on my profile) if you are interested.

**Comment by SimonBiggs** [comment]
@fzumstein I'm not sure if I have your email address. At the moment however I am on GitHub.

Certainly interested however. I have been considering dropping support and usage for xlwings because I simply can't guarantee it will continue to work from one release to the next due to unable to do appropriate CI.
