### ISSUE TITLE
is it possible to write/save in a stream (BytesIO for example)

### ISSUE THREAD

**Issue by ulyssejdv** [xlwings/xlwings#1121]
#### To do something like this

```python
wb = xw.Book()
sht = wb.sheets[0]
sht.range('A1').value = 'Foo 1'

storage_location = io.BytesIO()

wb.save(storage_location)
```

**Comment by fzumstein** [comment]
Why not just something like this? https://www.capatek-tutorials.com/python/uploading-files-to-sharepoint-with-python/

**Comment by ulyssejdv** [comment]
Hi,

I have no problem sending files to sharepoint. I want to avoid creating a file locally and just send a stream with my Excel content through HTTP.

Juste like https://python-pptx.readthedocs.io/en/latest/user/presentations.html?highlight=save#opening-a-file-like-presentation.

**Comment by fzumstein** [comment]
No this won't work. The difference is that xlwings is remote controlling Excel which in turn handles the file, while python-pptx is writing the file directly. You should be able to do it with something like xlwt, openpyxl or xlsxwriter.

**Comment by shushilchaurasiya** [comment]
Hi, a bit late to the party here. But I need to write a copy of my excel file to BytesIO and then open it in xlwings so that the formulas can be evaluated and then I can read the results using openpyxl from teh same excel file. Since I'm doing this for a web-applicatioin (streamlit), I don't want to have to the file to the disk. Is it in anyway possible at all?
