### ISSUE TITLE
Macros cannot be run unless workbook opened manually in Excel prior to running xlwings script

### ISSUE THREAD

**Issue by bklyons** [xlwings/xlwings#1152]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 Enterprise LTSC version 1809 OS build 17763.678

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.7.3 running in Spyder via Anaconda, Excel/Office 2016, xlwings 0.15.8

#### Describe your issue (incl. Traceback!)
When running a VBA macro from xlwings, I get these 'macro disabled or not found' errors if I do not have the workbook already open. In the File > Options > Trust Center > Trust Center Settings > Macro Settings, I have "Enable all macros" checked.

To get it to work after receiving this error message, I must:

1) Close all Excel windows open on my machine
2) Kill all Excel.exe process that are still running
3) Open the workbook manually using a fresh Excel instance
4) Run the script
```python
# Your traceback here
Traceback (most recent call last):

  File "<ipython-input-3-803b5dbc6ebc>", line 1, in <module>
    runfile('C:/Temp/xlw_macrotest.py', wdir='C:/Temp')

  File "C:\Users\blyons\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\blyons\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Temp/xlw_macrotest.py", line 14, in <module>
    macro()

  File "C:\Users\blyons\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 2720, in run
    return self.app.impl.run(self.macro, args)

  File "C:\Users\blyons\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 414, in run
    return self.xl.Run(macro, *args)

  File "C:\Users\blyons\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 63, in __call__
    v = self.__method(*args, **kwargs)

  File "<COMObject <unknown>>", line 14, in Run

  File "C:\Users\blyons\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)

com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', "Cannot run the macro ''test_macro.xlsm'!TestMacro'. The macro may not be available in this workbook or all macros may be disabled.", 'xlmain11.chm', 0, -2146827284), None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
I cannot attach a XLSM file, the macro is merely:

```
Sub TestMacro()
    Worksheets(1).Range("A1") = "Hello"
    Worksheets(1).Range("A2") = "World"
End Sub
```

```python
# Your code here
import xlwings as xw

if __name__ == '__main__':
    file = r'C:\Temp\test_macro.xlsm'
    wb = xw.Book(file)
    macro = wb.macro("TestMacro")
    macro()
```

**Comment by fzumstein** [comment]
Not sure, but you might want to test if it shows the same behaviour if you include the module name like this: `wb.macro("Module1.TestMacro")`

**Comment by bklyons** [comment]
Nope, still behaves the same.

**Comment by fzumstein** [comment]
Any chance that it's something that shows up here? https://stackoverflow.com/questions/18389562/cannot-run-the-macro-the-macro-may-not-be-available-in-this-workbook

**Comment by bklyons** [comment]
I’ve tried some of the things there to no avail.

I am trying to do it directly from VBS and I’m getting the same error so
it’s not an XLW issue, more a Windows issue. Could be some group policy,
Windows sysadmin kinda thing.

**Comment by fzumstein** [comment]
Fair enough! I am closing this issue then but feel free to post more info if you ever find out more.

**Comment by tomnewg** [comment]
Hi @bklyons,

I have the same issue. I overcame it a few times by programmatically clicking in a few cells once it opened up but it doesn't always work. I think it is not properly activated because if I open the file with xlwings and then manually click in Excel afterwards I can run the macro from python. I couldn't find a proper workaround yet. Did you find a solution in the end?

Many thanks

Tom

**Comment by bklyons** [comment]
I think these issues may be because of administrative controls on macros. If I have a xlw/py script which opens excel, commands xlw to open a file, and run a macro, it gets blocked. However, if I (1) start Excel from the command line (I'm in a bat script on Windows) (2) open the file in Excel from the command line (3) then have the python script run the macro that is in the file, it works. The administrative controls probably assume it's a file that I opened and not one that was magically opened through win32com. Maybe. Not great but it works.

**Comment by Wyko** [comment]
This issue is definitely still open for me! Sheets opened via xlwings always have macros disabled, no matter how far I open the trust center. The same sheet opened manually works fine.

I have a sheet with a module. The module contains the following:

```
Sub test()
    Range("A1").Value = "This is a test."
End Sub
```

Every time I call the method, it fails. Here's what I've tried, along with the errors I got:

# Open Sheet:
```
with xw.App(visible=True, add_book=False) as app:
    wb = app.books.open(r"test1.xlsm")
    ws: xw.Sheet = wb.sheets["Sheet1"]
```
# Attempts:
`wb.macro("test")()`

- `"Cannot run the macro ''test1.xlsm'!test'. The macro may not be available in this workbook or all macros may be disabled."`

**`app.macro("'test1.xlsm'!test")()`**
- `"Cannot run the macro ''test1.xlsm'!test'. The macro may not be available in this workbook or all macros may be disabled."`

**`app.api.Application.run("test")`**
- _Deadlocks_

**`wb.macro('Module1.test')()`**
- `Because of your security settings, macros have been disabled. To run macros, you need to reopen this workbook, and then choose to enable macros.`
