### ISSUE TITLE
ImportError: DLL load failed while importing win32api: The system cannot find the file specified.

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#1174]
Currently, when using `pywin32` with version 225, you will get this error message when trying to import xlwings.

**Comment by fzumstein** [comment]
This is a pywin32 issue that was introduced with 225, see: ImportError: DLL load failed while importing win32api: The system cannot find the file specified.

To resolve, run the script from the `Scripts` directory of your Python installation:

```
python C:\path\to\Scripts\pywin32_postinstall.py -install
```

**Comment by mhammond** [comment]
This is probably a different issue - #1406 tends to mean there are duplicate DLL files and the error message is something like "the specified procedure can not be found". This "cannot find the file specified" means that we can't find a single DLL. Is this python 3.8?

**Comment by fzumstein** [comment]
Continued in https://github.com/mhammond/pywin32/issues/1406

**Comment by j4iro** [comment]
After running the script the error persists, I am using mod_wsgi, apache, flask and python 3.8

**Comment by ahmedhindi** [comment]
I had the same problem and it was solved using `conda install -c anaconda pywin32`

**Comment by naveen1973** [comment]
Hi,
I am not able to get my jupyter notebook and lab working again. It was working just fine but since the last two months I am trying to fix things left, right and center.
Now I have the following issue:
    import win32api
ImportError: DLL load failed: The specified module could not be found.

I tried "conda install -c anaconda pywin32" but this did not solve the issue. Please can you help me further. It has been more two months now. Nothing seems to help.

thanks so much!
