### ISSUE TITLE
Index = False for create_report in xlwings.pro

### ISSUE THREAD

**Issue by adriancyt** [xlwings/xlwings#1361]
Hi, is there an option to not output the index of a pandas dataframe in the report when using the create_report function in xlwings.pro? If not, is there any hack on this? Thanks!

**Comment by fzumstein** [comment]
You could simply set the first column as index:

```
create_report(df=df.set_index('col1'))
```

**Comment by adriancyt** [comment]
Thanks, and how about if I do not want to include the header? Do I also need to set first row as header?

**Comment by fzumstein** [comment]
If you want to get rid of both, the easiest would be to turn it into a numpy array:

```
create_report(df=df.to_numpy())
```

**Comment by adriancyt** [comment]
Thanks for the quick reply!

**Comment by fzumstein** [comment]
Since xlwings 0.24.0, it is now possible to use filters in the template and change the display of the DataFrame without code changes:

* To hide the index: ``{{ df | noindex }}``
* To hide the header: ``{{ df | noheader }}``
* To hide both index and header: ``{{ df | body }}`` which is the same as ``{{ df | noindex | noheader }}``

See also: https://docs.xlwings.org/en/stable/reports.html#dataframes
