### ISSUE TITLE
Malicious macros were found with standalone module

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#1370]
https://support.microsoft.com/en-us/office/malicious-macros-were-found-9e461c61-69d1-4ea9-a386-9ad0deaccfdd?ns=excel&version=90&syslcid=1033&uilcid=1033&appver=zxl900&helpid=56779&ui=en-us&rs=en-us&ad=us

**Comment by fzumstein** [comment]
although code signing doesn't prevent false positives, like here: https://stackoverflow.com/questions/53213215/antivirus-false-positive-in-my-vba-excel-macro

What you can do, however, is on the bottom right in the windows task bar > go to Windows Security (shield icon) > virus & thread protection > protection history > maximize the entry and select "allow"

**Comment by karimyafi82** [comment]
Has any progress been done on this matter?

Strangely, when I try "RunMain", the python code runs well and accordingly the main function is run and returns fine to Excel. However, when I try to import functions or restart the UDF server, I get that nasty error 1000 stating that it could not create Python process and access is denied for the command "cmd.exe /K ...."

When I go to the protection history of Windows Security, there are no threats. Probably because many settings there are controlled by my company's administrator(?)

**Comment by fzumstein** [comment]
The commands work differently: RunPython (via the Run main button) runs a shell command while the UDFs access a dll. This might be blocked from your company, not sure.

**Comment by karimyafi82** [comment]
Thank you for your reply. Any more details about the DLL we're talking about?

**Comment by fzumstein** [comment]
The `xlwings-32.dll` and `xlwings-64.dll` that sit in the same directory as the `python.exe`

**Comment by Hamitka** [comment]
I have the same problem.
The reason was Antivirus Kaspersky, after remove it - the problem is gone.
