### ISSUE TITLE
Running macro from xlwings gives TypeError and optional parameter in VBA function

### ISSUE THREAD

**Issue by GreekQuant** [xlwings/xlwings#1474]
Hi everyone:

- firstly I would like to ask how can we treat optional parameters of a VBA function when calling it from python. I have tried to just omit but python throws an error. I have also tried to just please " " but I get a TypeError

- Secondly when a VBA function has as input parameters defined as Variant which in most cases this is the case for Arrays, and I try to input a list say or a numpy array or even a numpy array transformed in records then the macro returns a TypeError again see below :

_Objects for SAFEARRAYS must be sequences (of sequences) or a buffer object. _

I do not know what buffer object is exactly. Secondly is sequences referring to a specific data structure? 

Thank you for your help in advance. 

p.s. there is a method in R which translates all the data in COMArray version. [https://www.google.co.uk/amp/s/rdrr.io/a/github/omegahat/RDCOMClient/man/asCOMArray.html]()

**Comment by fzumstein** [comment]
* Optional parameters: Here's what works:
If your optional parameters are at the end, you can simply leave them away, otherwise, you'd have to provide a value for them. In theory, you'd probably should be able to provide `None` to skip over them, but this fails and I am not sure if there's a way to fix it. You might be able to work around it by providing something like `-1` and handling this on the VBA side.
* arrays are accepted as nested lists/tuples, so you could simply do `numpyarray.tolist()` and use this as your arg:

```python
import xlwings as xw
import numpy as np

book = xw.books.active
myarray = book.macro('Module1.MyArray')
arr = np.array([[1, 2], [3, 4]])
myarray(arr.tolist())
```

```vbnet
Function MyArray(arr)

Dim i As Long, j As Long

    For j = LBound(arr, 2) To UBound(arr, 2)
        For i = LBound(arr, 1) To UBound(arr, 1)
            Debug.Print "(" & i & "," & j & ")", arr(i, j)
        Next i
    Next j

End Function
```

**Comment by GreekQuant** [comment]
Thank you for your proposal Felix. It helped a lot. Actually I managed to make this work by sending just tuples of data. That is presumably because those inputs are read from VBA as variants and then transferred into an Array.

Main problem was caused by optional parameters. I changed the order of those and now everything works perfectly.
