### ISSUE TITLE
xlwings- edit links and change data source in workbook

### ISSUE THREAD

**Issue by Cbarrow98** [xlwings/xlwings#1720]
XWLINGS:  0.24.7   EXCEL: MICROSOFT 365 64-BIT   PYTHON: 3.8

As the title states i was wondering if there is a way you can edit a workbooks data source links in excel using xlwings or by calling a VBA function within xlwings using api ? I found this link on SO and was wondering if its possible ? https://stackoverflow.com/questions/47452637/excel-vba-macro-change-link-name

**Comment by ericbmoreira** [comment]
I cannot answer that question but I would like to know why you are looking to change the links? I ask because I came from an old Excel trading model that had 10+ links and it was a nightmare. I would much rather use xlwings to gather the data in the backend and then output it to Excel. So instead of having Excel workbooks linked together they can go get the data from each other through Python.

**Comment by fzumstein** [comment]
Yes, you can do that by using `.api` with the syntax of your SO post, see also: https://docs.xlwings.org/en/latest/missing_features.html

**Comment by Cbarrow98** [comment]
Okay thanks Felix, also a further unrelated question I updated xlwings a few days ago and have been struggling to get the api. to work where it does not produce an error but just stays executing and never respond's if that makes sense (see below for sh) ?

![image](https://user-images.githubusercontent.com/71831382/135086610-b7d2eef8-da7b-4e0f-8971-29c6b952c308.png)

**Comment by fzumstein** [comment]
`myrange.paste()` is actually implemented: https://docs.xlwings.org/en/latest/api.html#xlwings.Range.paste

**Comment by Cbarrow98** [comment]
thank you Felix you can close this now :)
