### ISSUE TITLE
Two extra Excel windows opens with xw.APP() and books.open combination

### ISSUE THREAD

**Issue by murathptest** [xlwings/xlwings#1801]
#### Latest xlwings, python and Excel 2013/16

Hi,
The below code worked very well and I was able to open two excel workbooks on two different excel instances.
The question is, I also noticed that two BLANK excel workbooks also openned as well.
Is there a way to stop this behavior?  
When I do xw.apps.keys(), I only see two instances but 4 excel windows.
Thanks in advance.

import xlwings as xw

app1 = xw.App()
app2 = xw.App()

book1 = app1.books.open(...)
book2 = app2.books.open(...)

**Comment by fzumstein** [comment]
you can try to set the `xw.App(add_book=False)`. It is, however, behaving as if you would open an Excel instance manually (this also has opens with a blank workbook). xlwings also requires at least one workbook open to communicate with Excel so that might sometimes lead to other issues.

Alternatively just close these workbooks don't need. Also note that an Excel window != Excel instance sind Excel 2013 or so.
