### ISSUE TITLE
Addin corrupted

### ISSUE THREAD

**Issue by maarten-betman** [xlwings/xlwings#1900]
#### System specs
OS: Windows 10 Enterprise 21H2
xlwings: 0.27.6 
Excel: Microsoft® Excel® for Microsoft 365 MSO (Version 2203 Build 16.0.15028.20152) 32-bit 
Python: 3.9.10

#### Describe your issue (incl. Traceback!)
The excel addin is giving following message on Application startup:
![image](https://user-images.githubusercontent.com/31029725/165191012-4915ae18-e123-4c1d-9c63-cd1f63cc0fcb.png)

Followed steps a set out in the docs:
`xlwings addin install`

Alternatively tried the standalone installation:
`xlwings quickstart myproject --standalone`

The latter won't open the excel workbook at all:
![image](https://user-images.githubusercontent.com/31029725/165191287-834d3e28-11b9-470e-a3fe-206338990cb0.png)

I'm suspecting it has something to do with the Office365 version. I've had similar problems when using the VBA-JSON modules. I worked around this at time by removing most of the `If #VBA7` and `If #MacOS` logic. Any advise on how I can get some info on what is causing Excel to think the addin is corrupted?

**Comment by fzumstein** [comment]
This sounds like an issue with your installation of Excel rather than with xlwings -- have you tried to "repair" your Excel installation? Also, is this something new? Note that since 0.27.0, xlwings includes VBA-JSON, so if it works below 0.27.0, it may just be something in that module. Although I can't reproduce it over here (and given that nobody else has reported the issue (on VBA-JSON neither), I'd rather assume the issue is with Excel).

**Comment by maarten-betman** [comment]
Thanks for the fast reply @fzumstein! I'm afraid you're right. Unfortunately it also happens on a computer of a co-worker and the error also occurs for versions below 0.27.0. Think it's due to some security settings on our computer.
