### ISSUE TITLE
xlwings problems if using Personal Macro Workbook (PERSONAL.XLSB)

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#204]
see: http://stackoverflow.com/questions/31276272/xlwings-problems-if-using-personal-macro-workbook-personal-xlsb

**Comment by sdementen** [comment]
FYI, the link to the stackoverflow question is broken

**Comment by bricklantern** [comment]
Any suggestions for a workaround on this?   Thank you for creating xlwings, by the way.  I absolutely LOVE it.

**Comment by fzumstein** [comment]
Hey @Paragraphix, as the stackoverflow link is broken, do you mind describing the issue in more detail? also, what do you mean by "don't want the macro inside of the document".

**Comment by Paragraphix** [comment]
No Problem @fzumstein,
in Excel you can save macros to a personal workbook "PERSONAL.XSLB" - see https://support.microsoft.com/en-us/office/copy-your-macros-to-a-personal-macro-workbook-aa439b90-f836-4381-97f0-6e4c3f5ee566

The Problem from what i could find online is that you could call a macro from the Personal workbook before using:
macro_vba = app.macro("'PERSONAL.XLSB'!my_macro") 

but this does not seem to work anymore - every post i find about it says it was broken with an update and never got fixed (resulting in this open issue here)

If i find the article again that lead me here i'll link it to you.
The reason for using the personal.xlsb in my case is really simple...

"pentaho data integration" does not work with excelfiles that contain macros but i can execute python script via shell so in order to store and run them they are saved in the Personal.xlsb - this way the macros can be run but the saved/opened Excelfile itself does not contain any macros.

The only other workaround iam fiddeling around with at the moment would be to try to get one macro file to write into another

**Comment by fzumstein** [comment]
thanks for the additional info! I'll need some time to look into this...

**Comment by Paragraphix** [comment]
That'd be awesome - thank you!

**Comment by fzumstein** [comment]
I think I've never really got the issue here, anyhow, the solution is simple, you just need to refer to the personal.xlsb workbook properly to run the macros contained therein:

```python
import xlwings as xw

wb = xw.Book("PERSONAL.xlsb")
mymacro = wb.macro("MyMacro")
mymacro()
```

**Comment by fzumstein** [comment]
See also: https://github.com/xlwings/xlwings/issues/1957
