### ISSUE TITLE
xlwings Server via Office Scripts not responsive

### ISSUE THREAD

**Issue by alexanderburkhard** [xlwings/xlwings#2156]
#### 0.28.6, Office 365, Python 3.10

Hello there, and first of all, what a phenomenal project! Using it on a daily basis!

I am currently trying to make the xlwings server work (trying it out on my local machine) as the add-in option gets blocked by the networks firewall (and no - network admin does not want to whitelist it... sigh). So I made the local server run with the demo folder and the included main.py and went the OfficeScripts route. However once I click **Run** in the Office Script after pasting the output of _xlwings copy os_... nothing happens, except the small pop up "The scipt ran with errors."

Is there anything I have to adjust in the xlwings copy os output, maybe in order to direct the script to my local server? 

I am stuck on this for a while now and really appreciate any guidance / help here!

Many many thanks and best wishes

![image](https://user-images.githubusercontent.com/111152693/216659773-724ffd1b-f94c-43d8-b95a-edd21fca314e.png)

**Comment by fzumstein** [comment]
You need to replace `"url"` in `main` with the address of your server. Now, since Office Scripts runs on Microsoft's servers, it can't directly reach your server on localhost. Instead, you'd have to expose it using something like ngrok as explained here: https://docs.xlwings.org/en/stable/remote_interpreter.html#part-i-backend Also, I think "..." is actually causing issues (this has already been fixed in newer versions), so simply replace with with "development" or something similar.

Alternatively, if working with ngrok is not an option, have a look at the the brand new release 0.29.0 which adds support for Office.js addins: https://docs.xlwings.org/en/stable/officejs_addins.html Unlike Office Scripts, Office.js runs on your local machine and can therefore directly talk to your web server on https://127.0.0.1:8000, no ngrok required there.

**Comment by fzumstein** [comment]
Forgot to mention that instead of ngrok you could also use a cloud-based IDE, such as GitPod or GitHub Codespaces, see the GitPod button on https://github.com/xlwings/xlwings-server-helloworld-fastapi

**Comment by alexanderburkhard** [comment]
the ngrok solution works perfectly fine! Just had to add the /hello endpoint after my ngrok link :) Many thanks!
