### ISSUE TITLE
 must all internal users install xlwings addin and python as well? 

### ISSUE THREAD

**Issue by Dulaclyon** [xlwings/xlwings#2389]
OS (Windows 11 Pro Operating system)
xlwings version: 0.30.13, Excel and Python (Office 365 for Enterprise, Python 3.12.1)

Describe your issue (incl. Traceback!)
I am new to python and Xlwings and strive to put what I have learned into my work. A general question I have a general question in mind,  using xlwings addin and placing my dashboard in onedrive, in order for all internal user to use my dashboard, and considering that many internal users are unfamiliar to python and xlwigns addin,   must all internal users install on their each and every user's computer xlwings addin and python as well?    thank you

**Comment by fzumstein** [comment]
The "best" way to handle it is to use Office.js add-ins with xlwings Server (part of xlwings PRO):
https://docs.xlwings.org/en/latest/pro/server/officejs_addins.html

Best, because you have a single Python installation on a self-hosted server (no local Python installation required) and you can distribute the add-in via the Office admin console without the end-users having to install it manually (also no VBA). It also works with the web-based version of Excel.

But there's other ways, too:

* Install Python and the source code on a shared drive (might be slow, depends on your network speed)
* The VBA add-in can also be distributed as part of the workbook itself ("standalone") version: https://docs.xlwings.org/en/latest/addin.html#alternative-standalone-vba-module
* You can also freeze your code into an exe and distribute that exe along with your workbook (doesn't work for UDFs though), then call RunFrozenPython: https://docs.xlwings.org/en/latest/deployment.html#runfrozenpython

**Comment by Dulaclyon** [comment]
Thank you for the clarification....
