### ISSUE TITLE
Opensource version compatibility

### ISSUE THREAD

**Issue by Abinashbunty** [xlwings/xlwings#2487]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10, 11

This is not necessarily a bug/feature issue, but more related to the opensource version of the package and its compatibility. For work, I am using xlwings. Wonderful package by the way with all the necessary components that I need at the moment. 😄 I had a couple of questions regarding the package which will help me in assisting the client accordingly before using the package for their work:

- Will the opensource version have Long-term-support (LTS) for future versions of Excel? I mean, Excel tends to get updated every now and then. With that, there might be a compatibility issues which can occur. So I was curious if LTS will be there for the opensource version. This is specifically related to the add-in functionality within Excel.
- Will the opensource version always remain opensource with NO change in the license?

Sorry for the questions in the Issue section, but I thought this would be the ideal way to address it. 😄 Given my future time constraints, I plan to also delve into the ongoing development of the package.

**Comment by fzumstein** [comment]
* Well, OSS is just that: OSS. There's no guarantees for LTS or anything. But if things break and I am not fixing it, you can, as it's OSS ;). Microsoft almost never deprecates something, so yes, it has worked for the last 10 years and I would expect it to work for the next 10 years too. However, since classic xlwings depends on VBA (if you use the add-in), they make it always more complicated to run VBA. And companies are getting more and more restrictive and anti-virus scanners also flag more and more. So, in summary: Excel will work just fine with xlwings also in the future, but external factors can block certain things. So to get around all that, there's now xlwings Server: https://github.com/xlwings/xlwings-server (it's not OSS, but source available and free for non-commercial use). And it ticks all the boxes for future-proof and enterprise-ready (no VBA, no local Python installation, central add-in deployment, UDF support on all platforms, SSO authentication, etc.)

* Yes, no plans for changing the license of existing OSS code.
