### ISSUE TITLE
Can't read correctly for large spreadsheet 

### ISSUE THREAD

**Issue by kuangxiaolong** [xlwings/xlwings#490]
xlwings can't read my sheet correctly and I have no idea. I am using mac and the version of Excel is 2016. Following is the code:

`import xlwings as xw`
`xw.Workbook("Sample")`
`st = xw.Sheet("Test")`
`a = xw.Range(st,"A1:BF646").value`
`print(type(a))`

`a` should be a list, while in this case, the output is 
`<class 'appscript.keywordwrapper.Keyword'>`

but when I change the range to 
`a = xw.Range(st,"A1:AB646").value`
then it is working and `a` is a list

Any idea why this happened? Thanks.

**Comment by fzumstein** [comment]
Whats does it print for `a`?

**Comment by kuangxiaolong** [comment]
it prints `k.missing_value`.

There are some blank cells in the table and that's probably the reason

**Comment by fzumstein** [comment]
can you send me a sample spreadsheet?
Am 17.06.2016 10:53 nachm. schrieb "kuangxiaolong" <notifications@github.com

**Comment by SeanCullen** [comment]
Where there any Excel errors in the range you are trying to read; between AB:BF ?

I'm experiencing a similar problem. When reading large arrays(ex. AK77:IL95) that contain errors (ex. #DIV/0!, #N/A) instead of returning a list, Excel 2016 15.32 crashes.

Is there a way of parsing error values so that they are returned as strings instead of as k.missing_value objects?

**Comment by DentonGentry** [comment]
I'm running into the same issue crashing Excel 2016 16.16.6 when I read from a spreadsheet range containing #DIV/0! or #N/A cells. Excel crashes with a stack trace that looks like AppleEvent processing, presumably the AppleEvents which xlwings sent to it.

If I modify the ranges being read, perhaps only reading 1-2 columns at a time instead of 3+ columns, sometimes I can get it to return results without crashing. However this implies that I know in advance where the problematic cells are and can modify my code to tiptoe near them.

This is enough of a problem that I'm considering writing VBA code to call as a macro from xlwings and pre-process the cells I want to read, transforming #DIV/0! and #N/A into something else which I can recognize in the Python code later.


\#  1  0x00007fff30c0f7b5 in _implArrayRelease(__CFAllocator const*, void const*) + 0x00000004 (AE + 0x00000000000147b5) 0x0000000000000000
\#  2  0x00007fff2f9a4088 in _CFArraySetValueAtIndex + 0x00000170 (CoreFoundation + 0x0000000000067088) 0x0000000000000000
\#  3  0x00007fff30c0f5d7 in AEListImpl::putElement(long, unsigned int, AEImpl const*) + 0x0000005F (AE + 0x00000000000145d7) 0x00007ffee97a0880
\#  4  0x00007fff30c13693 in _AEPutDesc + 0x000000AF (AE + 0x0000000000018693) 0x00007ffee97a08b0

**Comment by DentonGentry** [comment]
Filed the crash as https://github.com/ZoomerAnalytics/xlwings/issues/1028
(it is Excel's issue, filed the xlwings bug with information and a workaround for anyone else encountering it)

**Comment by fzumstein** [comment]
closing this in favor of #1028
