### ISSUE TITLE
"Apple event timed out" with getting/setting cell values

### ISSUE THREAD

**Issue by phillips199** [xlwings/xlwings#618]
I am running xlwings on a Mac using Excel for Mac v15.3. I am evaluating a number of different scenarios in a model, setting values and looking at values with calculation set to 'automatic'.  For some reason after getting/setting around 65-70 values, I get the following error:

appscript.reference.CommandError: Command failed:
		OSERROR: -1712
		MESSAGE: Apple event timed out.
		COMMAND: app(pid=35328).workbooks[2].worksheets['A5. Financing Assumptions'].cells['H29'].value.set(375.0) 

I have tried running the scenarios with calculation set to 'manual' and manually calculating the workbook (through xlwings) but get similar behavior after 65-70 actions.

I have monitored some basic data through psutil during this script and the number of threads and memory seem relatively stable.

Has anybody else experienced a similar issue?  I saw [this issue on autofit()](https://github.com/ZoomerAnalytics/xlwings/issues/74) generated the same error but that seemed to be an issue with appscript's implementation of autofit specifically.

**Comment by fzumstein** [comment]
Are you able to post a minimal example to replicate the issue?

**Comment by phillips199** [comment]
It turns out I am unable to reliably replicate the issue, but I have determined that the above error is generated when appscript attempts to communicate with Excel at a point when Mac OS considers Excel to be "(not responding)".  

So, I would no longer consider this to an xlwings or an appscript issue.  This "(not responding)" state can sometimes occur during a resource intensive recalculation.  Even changing values and recalculating manually appears to create the same behavior (at least for a few seconds) under the "right" circumstances.  The spreadsheet in question involves a number of iterative calculations that each probably involve over a thousand intermediate cell calculations. 

In any event, I think this issue can be closed.  Thanks.

**Comment by skiiver** [comment]
This issue is reliably replicated when writing "sufficiently large" pandas dataframes out to Excel.  I have run in to this in data science/reporting workflows.  

They python/xlwings/sql side will run perfectly with no resources spikes or similar.  

I think it would be helpful to keep the issue open and look in to it for several reasons. 

1. The timeouts can occur on dataframe sizes that, if already existing in an Excel tab, would not cause slow downs.  You can prove this by writing a dataframe that causes timeouts out to csv, then importing it into excel.  (This is also a short-term workaround for this xlwings/timeout situation when it occurs).   So it appears to be an issue with the piping arrangement rather than a limit to Excel on Mac. Admittedly though, I do not have any experience with intra-app communications on Mac.
2. The behavior is different on Windows, notably it is not replicable by increasing data table size.  So developing in mixed-OS workflows is impacted.  
3.While perfect OS-portability isn't likely, this seems like an area that could be addressed, or at least generate a user warning alerting them to the possibility of overloading the apple>excel pipe.

**Comment by jurasofish** [comment]
I had the same timeout error when saving a large workbook on mac.
In my case I determined using a debugger that xlwings was calling appscript and found that there is an optional timeout keyword argument that appscript can take: https://github.com/mattneub/appscript/blob/f6edd1e7e0fa25809f957ea442d37c7eb0eef5a7/py-appscript/trunk/appscript_3x/lib/appscript/reference.py#L399

Changing ```workbook.save()``` to ```workbook.api.save(timeout=3000)``` worked for me. Note that saving to a new path or anything else different might require calling different functions in the api.

Hope this is helpful! Only other issue I could find that refers to the timeout is #466

**Comment by scovail** [comment]
I recently experienced this issue as well, although it's intermittent. I encountered the problem when I was setting cell values in a worksheet with the following statement: tab.range('A2').value = df.values.tolist(). The data frame being used had dimensions of 33,430 rows x 7 columns. I'm wondering if there's a way to set a timeout value when assigning cell values. Thanks.

**Comment by hstarmans** [comment]
Also had this issue couldn't pass the optional parameter timeout, I simply adjusted the library with a new timeout.
You can find the location of the library with import app script, appscript.__file__   --> good luck

**Comment by fzumstein** [comment]
Timeouts that occur when reading/writing values has to be done via chunking -- planning to add this as an option, tracked in #77
