### ISSUE TITLE
Can't open .xlsm files

### ISSUE THREAD

**Issue by jason-s** [xlwings/xlwings#751]
I have an Excel 2007 file with macros. I don't care about the macros as long as they are left unmodified, I just want to read and write from the spreadsheets without modifying the macros.

I get an error when using xlwings 0.11.4 on Windows 7 with Excel 2007:

```
>>> b = xw.Book('aa1.xlsm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\xlwings\main.py", line 480, in __init__
    impl = app.books.open(fullname).impl
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\xlwings\main.py", line 2754, in open
    impl = self.impl.open(fullname)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\xlwings\_xlwindows.py", line 432, in open
    return Book(xl=self.xl.Open(fullname))
  File "<COMObject <unknown>>", line 8, in Open
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, u'Microsoft Office Excel', u"Excel cannot open the file 'aa1.xlsm' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.", u'C:\\Program Files (x86)\\Microsoft Office\\Office12\\1033\\XLMAIN11.CHM', 0, -2146827284), None)
```

**Comment by steezyTones** [comment]
I've run into the same issue using Excel 2011 on OSX 10.12.6. This isn't just limited to xlsm format, but also xlsb and possibly others.

One observation that may be helpful is that I only get this error message when I try to save a workbook under a new name. I receive a warning message saying "Visual Basic Macros will be removed if you save the file in this format" and an option to either "Cancel" (which terminates the python script) or "Save," which allows the script to continue running, but leaves me with the error that Jason's getting when I try to open the file. 

Although my current workaround is to simply save the file without changing its name (for instance, wb.save()) this is not ideal, as I'd like to have a new file created so that I can compare it to the old one in order to determine my code ran correctly.

Hope this helps - this is an awesome resource and I hope that this feedback helps make it even better!

**Comment by martmists** [comment]
I just opened my python shell trying to open the sheet though...

**Comment by fzumstein** [comment]
Looks to me as if the file extension might have been changed outside of Excel instead of using Excel's save as... feature?
