### ISSUE TITLE
How to create a messagebox?

### ISSUE THREAD

**Issue by NamelessUzer** [xlwings/xlwings#756]
I mean how to run the VBA function "MsgBox" in python, so that I can send something useful to users.

**Comment by tagomatech** [comment]
Depending on exactly what you  want to achieve this can be as simple as writing a VBA macro and calling it from pyrhon:

* Your macro VBA

```
Sub MyMsgBox()
    MsgBox "Hello World"
End Sub
```
* On the python side:

```
# Import Xlwings
import xlwings as xw

# Say you wrote your VBA function in the (sole) workbook currently opened
app = xw.apps[0]

# Activate your workbook (I am even not sure it is required)
app.activate()

# Assign your macro to a python variable and call it
my_msgBox_macro = app.macro('MyMsgBox')
my_msgBox_macro()
```
Actually, I was surprised it is that simple.

HTH

**Comment by skasi7** [comment]
You can try with:
```py
win32api.MessageBox(xw.apps.active.api.Hwnd, 'Hello world!', 'Info', win32con.MB_ICONINFORMATION)
```

**Comment by ericbmoreira** [comment]
Since this is still open, and I just worked with it, I will add this link. You can use it as Felix's example above, except you do not need the win32con. Just use the hexadecimal number. WITHOUT the 'L' at the end, as you will see in the link.
```
win32api.MessageBox(
  mybook.app.hwnd, 'Hello world!', 'Info', 0x00000040
)
```
I wanted an OK/Cancel window so I used the code below. If you assign a variable to it you will still get the window in Excel. Then the variable will be == 1 if it was OK, and == 2 if it was Cancel.
```
ok_cxl = win32api.MessageBox(
    wb.app.hwnd, 'a string from df.to_string()', 'Large Modifier Changes', 0x00000001
)
```

- https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox

**Comment by fzumstein** [comment]
* The AppleScript equivalent is:

  ```
  tell application "Microsoft Excel"
	  display dialog "hello"
  end tell
  ```

  With appscript, it's something like:
  https://github.com/hhas/appscript/blob/master/py-appscript/sample/osax/standard_additions.py
  
  although that's a generic alert. Might be able to attach it to the app like here:
  https://github.com/mattneub/appscript/blob/master/py-appscript/tags/py-appscript-0.16.2/Lib/osax/wrappers.py#L67-L86

* Google Apps Script:

  ```js
  SpreadsheetApp.getUi().alert("hello")
  ```

* Office Scripts: not sure if possible at all
