### ISSUE TITLE
Is there anyone could help:No command specified in the configuration, cannot autostart server 1000.

### ISSUE THREAD

**Issue by TianXinQC** [xlwings/xlwings#790]
when I click Import Functions I got:

Is there anyone could help:No command specified in the configuration, cannot autostart server 1000.
Make sure you are trusting access to the VBA project object module(Excel Option).

I uninstall and reinstall many times but I can't solve this problems.I'm going to be mad.

**Comment by mkhlvlkv** [comment]
We am having the same issue. I spent several days on this now, read your documentation inside out and backwards, and followed instructions EXACTLY. Still cannot get the UDF server to start properly. Can you please advise?

**Comment by mkhlvlkv** [comment]
I have no idea, because the version in __init__.py is set to "dev".
In any case, I cloned the latest source code just now, so I presume that corresponds to the latest version.

Setup: python 3.6.3, Excel 2010 (32-bit)

It worked before, but doesn't work any more. I am not sure if something changed with the codebase on your end, or if I broke something (more likely).

Can I run through my setup steps with you, and maybe you will notice if something looks wrong?

1. Opened the Visual Studio .sln and compiled xlwings32.dll under Release.
2. Opened up xlwings/__init__.py and changed __version__ to '0.1.0'
3. Make sure that all previous versions of the addin/dll are removed, using your instructions in the documentation.
4. python setup.py bdist_wheel
5. pip install dist/xlwings-0.1.0-py3-none-any.whl
6. Testing: python -c "import xlwings as xw; xw.serve()" // Looks good
7. xlwings addin install // Successfully installed the xlwings add-in! Please restart Excel.
8. Opening up udf.py example (so that we don't have to add references)
9. Verified ~/.xlwings/xlwings.conf file (I believe it is the same as it was before).
9. Clicked xlwings ribbon -> check "Debug UDFs".
10. Click "Import Functions" -> "No command specified in the configuration, cannot autostart server 1000."

Thanks a lot for your help! I have been trawling through the VBA and C++ code all day and I cannot see what is wrong.

**Comment by fzumstein** [comment]
you can't install from github. either use pip or conda or download from pypi: http://docs.xlwings.org/en/stable/installation.html

**Comment by mkhlvlkv** [comment]
I am not installing from github. I am building everything from your source, and we have our own pip/artifactory to accommodate. 

We are using a standalone Python, not Anaconda.

This is definitely not an issue of pip/github, as I was able to build/run it from your source code last month.

**Comment by fzumstein** [comment]
things changed at the beginning of the year. The package is now being built on appveyor, replacing dev tags with the correct version tag. You'd need to copy this procedure if you don't want to download the package from pypi: https://github.com/ZoomerAnalytics/xlwings/blob/master/appveyor.yml

**Comment by mkhlvlkv** [comment]
I am very confused. 

I don't see how the appveyor issue will affect me at all, if I am building and installing the package locally.

Is the source code on github up to date? If so, then I don't see how the appveyor script will affect me, or cause the issue that I am having.

Do you think this issue is in some way related to the fact that this was built from source?

**Comment by fzumstein** [comment]
yes, you should start off the pypi package. since this year, the version strings are not hardcoded anymore on the GH source, so they are being replaced with the correct version at build time. If you wanted to do the same from the GH source, you'd manually have to do what's happening in the appveyor build steps.

**Comment by jakjen** [comment]
This also happens to me: When I try to use the debug mode, I get the same error. The UDF works fine, but I cannot debug

**Comment by bushidoji** [comment]
^ I can echo what jakjen said above.

If "Debug UDFs" is checked, "No command specified in the configuration, cannot autostart server 1000." error will come up.

This is using xlwings v0.11.7 & python 3.6 (anaconda 3)

What is going on here?

**Comment by Colin-b** [comment]
In such a case you need to call the serve method as described here: http://docs.xlwings.org/en/stable/debugging.html?highlight=Serve

**Comment by cfytrok** [comment]
Have same problem. Everything work until I checked Debug UDFs. Calling serve method doesn't help.
Here is my udf.py.
```python
import xlwings as xw

@xw.func
def test(data):
    return data

if __name__ == '__main__':
    xw.serve()
```
 I run it in debug mode in PyCharm. Python 3.7.0. xlwings 0.15.1

**Comment by fzumstein** [comment]
You need to make sure that the interpreter which is in the config (e.g. Ribbon) is the one you run the script from.

**Comment by cfytrok** [comment]
I set Interpreter to "C:\Program Files (x86)\Python37-32\python.exe" in Excel Ribbon.
Pycharm prints in console:

> "C:\Program Files (x86)\Python37-32\python.exe" "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 60739 --file C:/test/udfs.py
pydev debugger: process 7932 is connecting
Connected to pydev debugger (build 181.4892.64)
xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}

So I think the interpreter is the same.
