### ISSUE TITLE
Passing a list of multiple ranges to a UDF

### ISSUE THREAD

**Issue by Lzm0010** [xlwings/xlwings#837]
I couldn't find if this is possible or not. I was trying to pass multiple (unknown amount of) ranges like this:

`sht.range(someRange).value = '=my_user_defined_function(namedRange1, namedRange2, namedRange3)' `

to my udf 

```
@xw.func
@xw.arg("ranges", pd.DataFrame) # i have tried other data types but couldn't figure what to use
@xw.ret(expand="table")
def my_user_defined_function(*ranges):
   # ranges is a DataFrame or list of ranges, do something with it
   for range in ranges:
      # do something
  return ranges
```

**Comment by fzumstein** [comment]
I don't think you can use decorators to do that. It should probably work though if you manually transform the nested lists into DataFrames within your function.

**Comment by Lzm0010** [comment]
Thanks Felix, I will give it a try that way

**Comment by DougAJ4** [comment]
My xlSciPy spreadsheet has several functions that use the ParamArray keyword in VBA to do what you want.

See: https://newtonexcelbach.com/2016/03/20/xlscipy-with-xlwings/

A VBA ParamArray is in effect a list of lists.  It can contain any number of variant arrays, values, text strings or other objects.

I originally created xlSciPy using ExcelPython, but with the current xlwings methodology you could:
Write your Python function with the xlwings decorator and a single argument
Import the python functions into the VBA xlwings module
Set up a separate VBA function to read the required arguments and convert them to a ParamArray, then call the xlwings function.

See the Special sheet and associated code from the download file at the link to see how they work.  The Excel UDF is xl_Special, in the m_Scipy module.

**Comment by Lzm0010** [comment]
Thanks Doug, I ended up doing it the way felix suggested, but for sure going to give that a look. Do you think this solution would increase the performance opposed to performing the conversions within a method?

**Comment by DougAJ4** [comment]
I don't know how the two approaches compare for performance.  I just went with the ParamArray approach because it seemed the simplest way to do it, and I'm still a lot more efficient when experimenting in VBA rather than Python.

A couple of points on the code in the xlSciPy spreadsheet:
I had a look at linking to an auto-generated xlwings UDF using a Paramarray, but it didn't work.  If you want to experiment with it, using the ExcelPython based code in the spreadsheet as a model (which still works) would be easiest.
I am also looking at changing from Python2 to Python3.  There seem to be some issues returning multiple arrays from Python3, which don't arise in Python2, so many of the xlSciPy UDFs return an error when using Python3.

I will raise new issues on these (or re-open an existing one in the case of the second) when I have time.

**Comment by DougAJ4** [comment]
It looks like issue 1 in my previous post is a non-issue, and issue 2 can be avoided by returning multiple values as a dictionary.

I have set up a short Python function to receive a ParamArray from an Excel UDF, and return it as d dictionary:
``
