### ISSUE TITLE
@xw.ret(expand='table') deleting nearby column

### ISSUE THREAD

**Issue by olivierhbh** [xlwings/xlwings#879]
I'm referring to that part of the doc:
> Also note that a dynamic array needs an empty row and column at the bottom and to the right and will overwrite existing data without warning.

Is that behaviour on purpose? Or is it difficult to change?

I'm writing a UDF similar to bloomberg BDH but the fact that it's clearing the adjacent column is a problem since I'm using parameters in the first rows and the first column (dates). Plus, I would also like to add other columns in between these UDF columns.

Or maybe I'm on the wrong path?

Thanks

**Comment by DougAJ4** [comment]
I guess that the reason for the blank row/column is to allow the user to differentiate the results of the UDF from the surrounding data.  

When an Excel function is entered as an array function, returning an array, the function is displayed in every cell, and you can't write over any individual cell or part of the output range.  You have to delete or modify the entire range.

With an xlwings UDF the function is only displayed in the top left hand corner, and all the other results display as values, so if you didn't have at least one blank row and column at the base and right there would be no way of telling where the UDF results stop and other data starts.

I agree that this feature is not optimal, but I am not sure what the solution is, other than using Excel array functions rather than the xlwings version.  For my own work that is what I usually do; that is return the results as an array and enter with Ctrl-Shift-Enter.  I also have two VBA macros that will resize the array to either the full extent, or to the size of the selected range.  These allow array output without the surrounding blank cells, but (as for the xlwings version) they will write over any data in the output range without warning and it clears the Undo data.  You can download a spreadsheet with examples of both this method and the xlwings way from:

(url)[xlwNumpy.zip](https://github.com/ZoomerAnalytics/xlwings/files/2033213/xlwNumpy.zip)

**Comment by olivierhbh** [comment]
I see, well that makes it obsolete for me, maybe it would be nice to have an option for it, so that users can use expand within a delimited range knowing the consequences.
Anyway, I will use a refresh function instead of a udf. Thanks for your answer.

**Comment by Louis-Alexis** [comment]
DougAJ4, your workbook is really nice ! effectively, use an udf with an excel array instead of expand='table' works well **but when **you don't know in advance** the size of the array**, it is not relevant i think ....

**Comment by xkeecs** [comment]
I also think returning a data frame should not delete nearby column. It's best if it can work as BDH() function in Bloomberg excel add-in.

**Comment by fzumstein** [comment]
This was fixed in 0.15.0
